### ISSUE TITLE
Net-Zero Metrics

### ISSUE THREAD

**Issue by jgunstone** [maxfordham/netzero-metrics#4]
```yaml
project_number: 6767
name: netzero-metrics
work_types: 
  - "FEE30" # 46 NZCB Project Metrics
project_drivers:
  - efficiency
  - quality
  - PR
director: HB
client: HPo
stakeholders:
  - MP
  - LB
  - GM
  - KD
delivery: 
  - JG
  - DK
  - OH
```
see https://wiki.maxfordham.com/Main/6667Q046NZCBProjectMetrics

### Meetings

when | who | description
-- | -- | --
03/05/2024 | LB, DK, JG | Initial conversations about project. Description given of suggested   briefing requirements.
03/10/2024 | HPo, LB, GM, DK, JG, OH | Net Zero Carbon team present their briefing information.
23/10/2024 | HPo, LB, JG | Development Team present back their interpretation of the brief. NZC Team happy with proposals, Dev Team to develop programme. 
12/12/2024 | LB, JG, DK, OH | Development Team present working version of app. Aim to deploy (make live) a beta release before Christmas.
: {tbl-colwidths="[15,15, 70]"}
